### ISSUE TITLE
执行docker run报错，unable to find image '8080:8080' locally

### ISSUE THREAD

**Issue by dary123** [nexptr/omnigram#2]
已经docker login了
![Uploading Dingtalk_20240103164513.jpg…]()

**Comment by exppii** [comment]
你的图挂了，不过我打个知道是什么问题。我最近一直完善快速启动的文档，只是还没有更新上来。 谢谢你提的问题。我会尽快解决

**Comment by dary123** [comment]
> 你的图挂了，不过我打个知道是什么问题。我最近一直完善快速启动的文档，只是还没有更新上来。 谢谢你提的问题。我会尽快解决

ok

**Comment by exppii** [comment]
当前应该已经解决了。参考最新的文档 https://omnigram.nexptr.com/zh/docs/overview/getting-started/ 或者 [omnigram-server](https://github.com/nexptr/omnigram-server) 当前已经重新推送docker 镜像 

另外： 
-  如果你只是使用者建议在1月底再来看看预计那个时候能出一个更加稳定的版本（开发者无所谓）；
-  当前只有我自己一个人在做维护，不管是文档，还是程序进度上不一定能很快跟上；

**Comment by dary123** [comment]
> 当前应该已经解决了。参考最新的文档 https://omnigram.nexptr.com/zh/docs/overview/getting-started/ 或者 [omnigram-server](https://github.com/nexptr/omnigram-server) 当前已经重新推送docker 镜像
> 
> 另外：
> 
> * 如果你只是使用者建议在1月底再来看看预计那个时候能出一个更加稳定的版本（开发者无所谓）；
> * 当前只有我自己一个人在做维护，不管是文档，还是程序进度上不一定能很快跟上；

好的，我试下，辛苦了

**Comment by dary123** [comment]
> 当前应该已经解决了。参考最新的文档 https://omnigram.nexptr.com/zh/docs/overview/getting-started/ 或者 [omnigram-server](https://github.com/nexptr/omnigram-server) 当前已经重新推送docker 镜像
> 
> 另外：
> 
> * 如果你只是使用者建议在1月底再来看看预计那个时候能出一个更加稳定的版本（开发者无所谓）；
> * 当前只有我自己一个人在做维护，不管是文档，还是程序进度上不一定能很快跟上；

端口号8080能换个吗，已经有其他项目用了这个
